enum ActionType {
  // SIGNUP = "SIGNUP",
  LOGIN = "LOGIN",
  PROFILE = "PROFILE",
  LOGOUT = "LOGOUT",
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY",
  CLEAR_CART = "CLEAR_CART",
  CLEAR_AUTH = "CLEAR_AUTH",

  UPDATE_AUTH = "UPDATE_AUTH",
  // DELETE_AUTH = "DELETE_AUTH",
  // ADD_TO_CART = "ADD_TO_CART",
  // REMOVE_PRODUCT_DATA = "REMOVE_PRODUCT_DATA"
}
export default ActionType;